spring:
  application:
    name: example
  sloth:
    remote:
      brokerUrl: 127.0.0.1:9001
      connectTimeout: 3000
    producer:
      enabled: true
      timeout: 1000
      messageMaxBytes: 4096
      retryTimes: 2
      retryInterval: 200
logging:
  level:
    com.tsingj.sloth: info