spring:
  application:
    name: example
  sloth:
    remote:
      brokerUrl: 127.0.0.1:9000
      onceTalkTimeout: 1000
      connectTimeout: 3100
    consumers:
      test-topic:
        topic: test-topic
        groupName: test-topic-group
logging:
  level:
    com.tsingj.sloth: info